FORCE_EVAL:
  METHOD: Quickstep
  DFT:
    BASIS_SET_FILE_NAME: BASIS_MOLOPT
    POTENTIAL_FILE_NAME: POTENTIAL
    SCF:
      SCF_GUESS: ATOMIC
      EPS_SCF: '1.0E-7'
      MAX_SCF: '300'
    XC:
      XC_FUNCTIONAL:
        _: PBE
VIBRATIONAL_ANALYSIS:
  NPROC_REP: '1'
  DX: '0.01'
  FULLY_PERIODIC: '.TRUE.'
