FORCE_EVAL:
  METHOD: Quickstep
  DFT:
    BASIS_SET_FILE_NAME: BASIS_MOLOPT
    POTENTIAL_FILE_NAME: POTENTIAL
    POISSON:
      PERIODIC: NONE
      PSOLVER: WAVELET
    SCF:
      SCF_GUESS: ATOMIC
      EPS_SCF: '1.0E-6'
      MAX_SCF: '300'
    XC:
      XC_FUNCTIONAL:
        _: PBE
