FORCE_EVAL:
  METHOD: Quickstep
  DFT:
    BASIS_SET_FILE_NAME: BASIS_MOLOPT
    POTENTIAL_FILE_NAME: POTENTIAL
    SCF:
      SCF_GUESS: ATOMIC
      EPS_SCF: '1.0E-6'
      MAX_SCF: '300'
    XC:
      XC_FUNCTIONAL:
        _: PBE
MOTION:
  BAND:
    BAND_TYPE: CI-NEB
    NUMBER_OF_REPLICA: '8'
    K_SPRING: '0.05'
    CONVERGENCE_CONTROL:
      MAX_FORCE: '0.0010'
      RMS_FORCE: '0.0050'
    ROTATE_FRAMES: 'TRUE'
    ALIGN_FRAMES: '.TRUE.'
    CI_NEB:
      NSTEPS_IT: '2'
    OPTIMIZE_BAND:
      OPT_TYPE: DIIS
      OPTIMIZE_END_POINTS: '.FALSE.'
      DIIS:
        MAX_STEPS: '1000'
